services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: weather-api
      POSTGRES_PASSWORD: changemeinprod!
      POSTGRES_DB: weatherdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U weather-api -d weatherdb"]
      interval: 5s
      timeout: 5s
      retries: 5